// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemporalTable.Data;

#nullable disable

namespace TemporalTable.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20240913084651_SetupMigration")]
    partial class SetupMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemporalTable.Models.AuthorEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AuthorCreation")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("AuthorCreation");

                    b.Property<DateTime>("AuthorRemoval")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("AuthorRemoval");

                    b.Property<DateTimeOffset>("BirthDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("BirthDate")
                        .HasColumnOrder(12);

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DeletedAt")
                        .HasColumnOrder(30);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("FirstName")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted")
                        .HasColumnOrder(13);

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("SecondName")
                        .HasColumnOrder(11);

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version")
                        .HasColumnOrder(14);

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FirstName" }, "IX_Author_FirstName");

                    b.ToTable("Authors");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("AuthorsHistory");
                                ttb
                                    .HasPeriodStart("AuthorCreation")
                                    .HasColumnName("AuthorCreation");
                                ttb
                                    .HasPeriodEnd("AuthorRemoval")
                                    .HasColumnName("AuthorRemoval");
                            }));
                });

            modelBuilder.Entity("TemporalTable.Models.BookEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id")
                        .HasColumnOrder(1);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("AuthorId")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("BookCreation")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("BookCreation");

                    b.Property<DateTime>("BookRemoval")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("BookRemoval");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DeletedAt")
                        .HasColumnOrder(30);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted")
                        .HasColumnOrder(14);

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Isbn")
                        .HasColumnOrder(10);

                    b.Property<int>("Pages")
                        .HasColumnType("int")
                        .HasColumnName("Pages")
                        .HasColumnOrder(12);

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("Price")
                        .HasColumnOrder(13);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title")
                        .HasColumnOrder(11);

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("Version")
                        .HasColumnOrder(15);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex(new[] { "Title" }, "IX_Books_Title");

                    b.HasIndex(new[] { "Isbn" }, "UX_Books_Isbn")
                        .IsUnique();

                    b.ToTable("Books");

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("BooksHistory");
                                ttb
                                    .HasPeriodStart("BookCreation")
                                    .HasColumnName("BookCreation");
                                ttb
                                    .HasPeriodEnd("BookRemoval")
                                    .HasColumnName("BookRemoval");
                            }));
                });

            modelBuilder.Entity("TemporalTable.Models.BookEntity", b =>
                {
                    b.HasOne("TemporalTable.Models.AuthorEntity", null)
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemporalTable.Models.AuthorEntity", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
